name: Hatch Build and Publish
run-name: HATCH to PyPI by @${{ github.actor }}

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: release
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install hatch
      - name: Build package
        run: |
          hatch version fix
          hatch build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@v1.8.11
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Update the about.py file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update about.py file"
          file_pattern: "about.py"
          status_options: '--untracked-files=no'
