name: Hatch Build and Publish
run-name: HATCH to PyPI by @${{ github.actor }}

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.check_step.outputs.branch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get current branch
        id: check_step
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw##*/}
          echo "{name}=branch" >> $GITHUB_OUTPUT
          echo "Branch is $branch."


  deploy:
    runs-on: ubuntu-latest
    environment: release
    needs: check
    steps:
#      - uses: nelonoel/branch-name@v1.0.1
#
#      - name: Which ref
#        id: branch-name
#        run: |
#          if [[ "${{ github.event_name }}" == "push" ]]; then
#            echo "REF=master" >> $GITHUB_ENV
#          else
#              echo "REF=${{ steps.branch-name.outputs.branch-name }}" >> $GITHUB_ENV
#            fi
      - name: Decode ref
        id: decode_ref
        run: |
          name=${{ needs.check.outputs.branch-name }}
          echo "Encoded ref is $name"
          name=$(echo $name | base64 -d)
          echo "Decoded ref is $name"
          echo "REF=$name" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            ref: ${{ env.REF }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install hatch

      - name: Build package
        run: |
          hatch version fix
          hatch build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@v1.8.11
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/ # uncomment for test.pypi.org

      - name: Update the about.py file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update about.py file"
          file_pattern: "pellipop/__about__.py"
          status_options: '--untracked-files=no'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: ${{ env.REF }}
