name: Cross-platform executable
run-name: PyInstaller by @${{ github.actor }}

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write
  deployments: write



defaults:
  run:
    shell: bash

jobs:
#  release:
#    name: Release binaries
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4
#      - name: Create Release
#        uses: elgohr/Github-Release-Action@main
#        env:
#          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          title: MyReleaseMessage
#          tag_name: ${{ github.ref }}
#    outputs:
#        upload_url: ${{ steps.create_release.outputs.upload_url }}
#        version: ${{ steps.create_release.outputs.tag }}

  build:
    name: Build release binaries

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

#    needs:
#      - release


    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Install pellipop
        run: |
          pip install .

      - name: Build with pyinstaller
        run: |
          pyinstaller pellipop/gui.py \
          --onefile \
          --name=pellipop-${{ matrix.os }} \
          --hidden-import='PIL._tkinter_finder' \
          --windowed

      - name: Deploy artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pellipop-${{ matrix.os }}
          path: ./dist/pellipop-${{ matrix.os }}*
          if-no-files-found: error

#      - name: Add artifact to the release
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
#        with:
#          upload_url: ${{ needs.release.outputs.upload_url }}
#          asset_path: ./dist/pellipop-${{ matrix.os }}*
#          asset_name: pellipop-${{ matrix.os }}
#          asset_content_type: application/zip




      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: pellipop-${{ matrix.os }}
          tag_name: test
          files: ./dist/pellipop-${{ matrix.os }}*
          body: |
            Pellipop release for ${{ matrix.os }}
          draft: false
          prerelease: false

